### ISSUE TITLE
adding a field fails for value containing '='

### ISSUE THREAD

**Issue by HendrikR** [muennich/oggted#1]
oggted fails to add/replace a field using the --add-field KEY=VAL (or --replace-field KEY=VAL) syntax if VAL contains an '=' character, whether VAL is quoted or not.

    oggted -f WXXX='foo=bar' file.ogg
    # oggted: invalid argument for option -70: WXXX=bla\=blubb
    oggted -f WXXX='foo.bar' file.ogg
    # succeeds

This can easily be fixed with a small change in `options.cpp`, line 70+:

    --- a/options.cpp
    +++ b/options.cpp
    @@ -68,8 +68,7 @@ bool Options::parseCommandLine(int argc, char **argv) {
        /* modification of fields */
        case 'F':
        case 'f':
    -               if (!(sep = strchr(optarg, '=')) || !(vlen = strlen(sep + 1)) ||
    -                               strchr(sep + 1, '=')) {
    +               if (!(sep = strchr(optarg, '=')) || !(vlen = strlen(sep + 1))) {
                        cerr << command << ": invalid argument for option -" << opt << ": "
                             << optarg << endl;
                        exit(1);

**Comment by xyb3rt** [comment]
Fixed by pull request #2.
